### ISSUE TITLE
Hi, I'm facing a problem like this in my project.

### ISSUE THREAD

**Issue by adhithyagnair** [am5a03/viewstubfragment-demo#1]

**Comment by adhithyagnair** [comment]
Sorry for the actions above.

I'm not able to achieve the solution with this implementation in my project.
I have seen that `setUserVisibleHint` and `getUserVisibleHint` seems deprecated.
Can you provide any update for this one?

**Comment by am5a03** [comment]
Yes, it's deprecated in AndroidX, 
You may refer to this SO question:

https://stackoverflow.com/questions/57885849/in-androidx-fragment-app-fragment-setuservisiblehint-is-deprecated-and-not-exec

1. Create `FragmentPagerAdapter` like this
 `FragmentPagerAdapter(fragmentManager, BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT)`
2. Then you may determine the `Fragment` is visible or not in `onPause()` and `onResume()` 

I don't have time to update my repository at the moment, may be you can try to see if that works? :)

**Comment by am5a03** [comment]
Fixed in latest master
